### ISSUE TITLE
item service

### ISSUE THREAD

**Issue by way21x** [suraneti/roguard-clone-data-service#23]
would you continue to develop item service?

**Comment by suraneti** [comment]
@way21x sure.

**Comment by way21x** [comment]
i edited some code which make the Json files combine to 1 Json  instead of pages name, and added id to each items, mind me to commit?

**Comment by suraneti** [comment]
@way21x feel free to create a pull request :)

**Comment by suraneti** [comment]
@way21x I've pushed item service feature on commit `f1ade06`.
